Create .gitkeep
kevinwang09/learningtower_masonry pull request #5
Opened 2024-09-09 05:32 UTC by grc54

Upload the raw data folder to have proper data structure

2024-09-15 23:23 UTC, kevinwang09 requested changes

2024-09-15 23:23 UTC, kevinwang09 commented on Code/student_bind_rows.Rmd
> +fe1ma2 = function(x){
If you have created this function, you should use it on previous years too. Double check if 1 and 2 are consistently coded as females and males in that order.

2024-09-17 12:59 UTC, grc54 commented on Code/student_bind_rows.Rmd
> +fe1ma2 = function(x){
I have made sure the gender code is consistent and applied to previous years

2024-09-18 00:27 UTC, kevinwang09 approved these changes
LGTM

2024-09-18 03:37 UTC, merged